# Generated by Django 6.0.2 on 2026-02-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("data_json", models.JSONField()),
                ("total_count", models.IntegerField()),
                ("avg_temp", models.FloatField()),
                ("avg_pressure", models.FloatField()),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
