# Generated by Django 6.0.2 on 2026-02-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentdataset",
            name="avg_flowrate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="equipmentdataset",
            name="type_distribution",
            field=models.JSONField(default=dict),
        ),
    ]
